#version: "2.4"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboardpass
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5
  rails:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
